before_commands:
    - "composer install"

build:
  # Runs before inferred commands
  before:
    - ''
  environment:
    php:
      version: '7.1'
      ini:
        'date.timezone': 'Europe/Amsterdam'
  tests:
    override:
      - command: 'vendor/bin/phpunit --coverage-clover=coverage-report'
        coverage:
          file: 'coverage-report'
          format: 'clover'

tools:
  php_code_coverage: true
  php_code_sniffer:
      enabled: true
      config:
          standard: PSR2
      filter:
          paths: ["src/*", "test/*"]
  php_cpd:
      enabled: true
      excluded_dirs: ["test", "vendor"]
  php_cs_fixer:
      enabled: true
      config:
          level: all
      filter:
          paths: ["src/*", "test/*"]
  php_loc:
      enabled: true
      excluded_dirs: ["test", "vendor"]
  php_mess_detector:
      enabled: true
      filter:
          paths: ["src/*"]
  php_pdepend:
      enabled: true
      excluded_dirs: ["test", "vendor"]
  php_analyzer: true
  php_analyzer:
      filter:
          paths: ["src/*", "test/*"]
  sensiolabs_security_checker: true
